//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramManager.Client.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IStationsService")]
    public interface IStationsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationsService/GetStationList", ReplyAction="http://tempuri.org/IStationsService/GetStationListResponse")]
        string[] GetStationList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationsService/GetFCCList", ReplyAction="http://tempuri.org/IStationsService/GetFCCListResponse")]
        string[] GetFCCList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationsService/GetTypeList", ReplyAction="http://tempuri.org/IStationsService/GetTypeListResponse")]
        string[] GetTypeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationsService/GetStationInfo", ReplyAction="http://tempuri.org/IStationsService/GetStationInfoResponse")]
        ProgramManager.CoreObjects.StationInformation GetStationInfo(string stationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationsService/UploadStation", ReplyAction="http://tempuri.org/IStationsService/UploadStationResponse")]
        void UploadStation(ProgramManager.CoreObjects.Station station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationsService/DownloadStation", ReplyAction="http://tempuri.org/IStationsService/DownloadStationResponse")]
        ProgramManager.CoreObjects.Station DownloadStation(string stationName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStationsServiceChannel : ProgramManager.Client.Service.IStationsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StationsServiceClient : System.ServiceModel.ClientBase<ProgramManager.Client.Service.IStationsService>, ProgramManager.Client.Service.IStationsService {
        
        public StationsServiceClient() {
        }
        
        public StationsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StationsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StationsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StationsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetStationList() {
            return base.Channel.GetStationList();
        }
        
        public string[] GetFCCList() {
            return base.Channel.GetFCCList();
        }
        
        public string[] GetTypeList() {
            return base.Channel.GetTypeList();
        }
        
        public ProgramManager.CoreObjects.StationInformation GetStationInfo(string stationName) {
            return base.Channel.GetStationInfo(stationName);
        }
        
        public void UploadStation(ProgramManager.CoreObjects.Station station) {
            base.Channel.UploadStation(station);
        }
        
        public ProgramManager.CoreObjects.Station DownloadStation(string stationName) {
            return base.Channel.DownloadStation(stationName);
        }
    }
}
